export const SAVE_INFO_PLAYER = 'SAVE_INFO_PLAYER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const IS_LOADING = 'IS_LOADING';
export const REQUEST_SHOW_MILHAO_SUCESS = 'REQUEST_SHOW_MILHAO_SUCESS';
export const IS_LOADING_QUESTIONS_SHOW = 'IS_LOADING_QUESTIONS_SHOW';
export const REQUEST_QUESTIONS_SHOW_SUCESS = 'REQUEST_QUESTIONS_SHOW_SUCESS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
