export const SAVE_INFO_PLAYER = 'SAVE_INFO_PLAYER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const IS_LOADING_SHOW_MILHAO = 'IS_LOADING_SHOW_MILHAO';
export const REQUEST_SHOW_MILHAO_SUCESS = 'REQUEST_SHOW_MILHAO_SUCESS';
export const REQUEST_SHOW_MILHAO_FAILED = 'REQUEST_SHOW_MILHAO_FAILED';
